Installing new version of config file /etc/java-11-openjdk/security/default.policy ...
Installing new version of config file /etc/java-11-openjdk/security/java.security ...
Installing new version of config file /etc/java-11-openjdk/security/policy/README.txt ...
Setting up openjdk-8-jre:amd64 (8u372-ga~us1-0ubuntu1~18.04) ...
Setting up apturl-common (0.5.2ubuntu14.2) ...
Setting up python3-aptdaemon (1.1.1+bzr982-0ubuntu19.5) ...
Setting up libreoffice-style-tango (1:6.0.7-0ubuntu0.18.04.13) ...
Setting up python3-distupgrade (1:18.04.45) ...
Setting up default-jre-headless (2:1.11-68ubuntu1~18.04.1) ...
Setting up openjdk-11-jre:amd64 (11.0.19+7~us1-0ubuntu1~18.04.1) ...
Setting up libreoffice-common (1:6.0.7-0ubuntu0.18.04.13) ...
Installing new version of config file /etc/apparmor.d/usr.lib.libreoffice.program.senddoc ...
Installing new version of config file /etc/apparmor.d/usr.lib.libreoffice.program.soffice.bin ...
Setting up libreoffice-l10n-pt (1:6.0.7-0ubuntu0.18.04.10) ...
Setting up libreoffice-l10n-ru (1:6.0.7-0ubuntu0.18.04.10) ...
Setting up default-jre (2:1.11-68ubuntu1~18.04.1) ...
Setting up python3-aptdaemon.gtk3widgets (1.1.1+bzr982-0ubuntu19.5) ...
Setting up libreoffice-l10n-es (1:6.0.7-0ubuntu0.18.04.10) ...
Setting up libreoffice-core (1:6.0.7-0ubuntu0.18.04.13) ...
Setting up ubuntu-release-upgrader-core (1:18.04.45) ...

Configuration file '/etc/update-manager/release-upgrades'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** release-upgrades (Y/I/N/O/D/Z) [default=N] ?
